---
###### Setup pushgateway Server####
- name: get all ip
  debug: 
    var: ansible_all_ipv4_addresses

- name: get default ip
  debug: 
    var: ansible_default_ipv4.address

- name: Add group pushgateway
  group: 
    name: pushgateway
    state: present

- name: Add user pushgateway
  user: 
    name: pushgateway
    group: pushgateway
    state: present
    shell: /usr/sbin/nologin
    create_home: false

- name: Setup pushgateway folders
  file:
    path: "{{ item }}"
    state: directory
    owner: pushgateway
    group: pushgateway
  with_items:
    - /opt/pushgateway
    - /var/pushgateway
    - /etc/pushgateway

- name: Download pushgateway tar ball
  get_url: 
    url: https://github.com/prometheus/pushgateway/releases/download/v{{PUSHGATEWAY_VERSION}}/pushgateway-{{PUSHGATEWAY_VERSION}}.linux-amd64.tar.gz
    dest: /opt/pushgateway/pushgateway-{{PUSHGATEWAY_VERSION}}.linux-amd64.tar.gz

- name: Unarchive pushgateway tar ball
  unarchive:
    src: /opt/pushgateway/pushgateway-{{PUSHGATEWAY_VERSION}}.linux-amd64.tar.gz
    dest: /opt/pushgateway/
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: Copy binary files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
    owner: pushgateway
    group: pushgateway
    mode: '0755'
  with_items:
      - { src: '/opt/pushgateway/pushgateway', dest: '/usr/local/bin/' }
  notify:
    - restart pushgateway

- name: Copy systemd file
  copy:
    src: pushgateway.service
    dest: /etc/systemd/system/pushgateway.service
  notify:
    - restart pushgateway

- name: Allow intra net access to pushgateway
  iptables:
    chain: INPUT
    protocol: tcp
    source: 10.0.0.0/8
    destination_port: '9091'
    jump: ACCEPT
    

      

    
      
    